### ISSUE TITLE
Homepage - Primary Services section: Thumbnail alignments of post items should apply standard top to bottom, left to right.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/GP-Sytems#14]
![image](https://cloud.githubusercontent.com/assets/11186304/7450164/519af648-f274-11e4-9caa-de64284e2d31.png)

**Comment by arielcebudigital** [comment]
base on design brief:
Our Services - 3 primary services – Right hand column to have sub nav

**Comment by dsigue** [comment]
The problem verified fixed as the services will only display 3 items to avoid distorted and confusion
