### ISSUE TITLE
Homepage - How To Start section: This should be implemented as ACF field WYSIWYG and Pagelink at the backend as per Project Scope instruction #27.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/GP-Sytems#15]
![image](https://cloud.githubusercontent.com/assets/11186304/7450237/1a74a0d2-f275-11e4-86fa-5f2b1e4e9262.png)

**Comment by dsigue** [comment]
This is somehow related to bug # 16. Not yet fixed and updated
