### ISSUE TITLE
Homepage - Content section: Sub heading titles (H2, H3 and so on) font style should be consistent to the inner pages font format styling.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/GP-Sytems#25]
Expected: 
Font family: RobotoSlab Regular
Font size main base (H2): 25px
Font color: #eda906

![image](https://cloud.githubusercontent.com/assets/11186304/7451310/09f4f290-f282-11e4-8224-8e733a8e6c2c.png)

**Comment by dsigue** [comment]
Not yet updated and fixed.

**Comment by arielcebudigital** [comment]
clear cache,

Homepage
![gp-home](https://cloud.githubusercontent.com/assets/11186408/7744692/0901a97e-ffd8-11e4-9ee3-425570b0ede2.png)


Inner Page
![gp-inner](https://cloud.githubusercontent.com/assets/11186408/7744696/0f7c3e9a-ffd8-11e4-9799-648883c5b286.png)

**Comment by dsigue** [comment]
This is not invalid, so I'm going to flag this as fixed since the content shows the actual behavior. Thanks
