### ISSUE TITLE
Inner pages - Sidebar section: Sidebar box is floating when scrolling down the page.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/GP-Sytems#27]
![image](https://cloud.githubusercontent.com/assets/11186304/7466070/6e9070fc-f30f-11e4-82db-218c65dc3fa8.png)

**Comment by arielcebudigital** [comment]
Base on Project Scope task #33

Sidebar right section:
- This will be sticky
- Contact Us Today refer to Sidebar section
- Service items will be from Our Services custom posts, ensure to anchor link to their respective post
