### ISSUE TITLE
Our Services page - Enquire Now button: Title and Link fields should be place below the Message field on the submission sent to the email.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/GP-Sytems#30]
![image](https://cloud.githubusercontent.com/assets/11186304/7466208/7e526890-f311-11e4-80b8-d5c9d2862536.png)

**Comment by arielcebudigital** [comment]
This is not a bug

**Comment by arielcebudigital** [comment]
There is no standard for form output..
