### ISSUE TITLE
Gallery page: Please make the pagination button styling consistent to the other pages pagination button style.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/GP-Sytems#47]
![image](https://cloud.githubusercontent.com/assets/11186304/7467290/f460e1a4-f327-11e4-8bef-df9d8dfa791b.png)

**Comment by dsigue** [comment]
The pagination layout haven't yet updated and change just like the way on the other pages do.

**Comment by arielcebudigital** [comment]
please try to clear cache
