### ISSUE TITLE
Gallery page: Gallery thumbnail images should fit atleast 2 columns in iPad 2 mobile devices view.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/GP-Sytems#54]
![image](https://cloud.githubusercontent.com/assets/11186304/7467961/294881ee-f335-11e4-8f5c-847e9624960b.png)

**Comment by arielcebudigital** [comment]
This is not a bug, when you try using landscape it will automatically adjust to two...it will depend on the screen.

**Comment by dsigue** [comment]
Trying to do landscape view to the said mobile device, indeed it still the same only one column will then display. As per Luz, for enhancement I think, gallery images should display at least 2 columns to look good.

**Comment by arielcebudigital** [comment]
![screenshot-1](https://cloud.githubusercontent.com/assets/11186408/7740005/4276b298-ff9d-11e4-9101-fbdc66340fda.png)
![screenshot-2](https://cloud.githubusercontent.com/assets/11186408/7740007/502d2980-ff9d-11e4-93d5-15860f083297.png)

**Comment by dsigue** [comment]
Saw the screenshot ,what would the the comparison on the issue itself. The actual ipad air mobile device it will only show one column just the way on the 2nd screenshot via landscape view. Anyway if that's how it styled and designed, then I'll consider this as  not a bug. Please advise. Thanks

**Comment by arielcebudigital** [comment]
Yes make it not a bug, actually its only enchancement
