### ISSUE TITLE
Footer section: Font sizes of menu items and web design text should be consistent in all mobile devices view.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/GP-Sytems#56]
Samsung S4
iTouch 5

![image](https://cloud.githubusercontent.com/assets/11186304/7467989/7c45a476-f335-11e4-866b-b605d2b42ad8.png)

**Comment by arielcebudigital** [comment]
It's not the same font size, you can check the PSD..

**Comment by dsigue** [comment]
Check on PSD specs the font size are the same. Kindly check in your end, thanks

**Comment by arielcebudigital** [comment]
![footer-section](https://cloud.githubusercontent.com/assets/11186408/7740167/c185d6fc-ff9f-11e4-86de-85fe57a7b89e.png)

This is from mobile PSD

**Comment by arielcebudigital** [comment]
here is the footer of mobile

**Comment by arielcebudigital** [comment]
here is the footer of mobile
![gb-footer](https://cloud.githubusercontent.com/assets/11186408/7763089/68806462-006e-11e5-8e28-35e4d17b524c.png)
