### ISSUE TITLE
Inner page : Side bar menu:   Where we can edit and update the Contact Us Today side bar menu

### ISSUE THREAD

**Issue by dsigue** [titan-cebu/GP-Sytems#59]
![global sidebar_01](https://cloud.githubusercontent.com/assets/11186386/7765124/2464b21e-008d-11e5-95b4-207d80e0b643.jpg)

**Comment by arielcebudigital** [comment]
You can edit the Contact Us Today in Global Options

**Comment by dsigue** [comment]
Okay, already found it, Thanks .
